sudo: required

services:
  - docker

language: node_js

os:
  - linux

node_js:
  - "8"

before_script:
  - npm i @npm-wharf/shipwright@latest -g

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - shipwright build image --repo=npmwharf --name=kickerd-nginx --tags=lm,v,miv,ma --cache-from-latest